[package]
name = "savings_goal"
version = "0.1.0"
description = "Rizq savings goal program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "savings_goal"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
default = []

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl = "0.31.1"
